FirstProject/src/objects/Order_Table__c.object
<CustomObject>
    <description>Information about orders.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Order Tables</relationshipLabel>
        <relationshipName>Order_Tables</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Amount__c</fullName>
        <label>Order Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product_Table__c</referenceTo>
        <relationshipLabel>Order Tables</relationshipLabel>
        <relationshipName>Order_Tables</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Units__c</fullName>
        <label>Units</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Order Table</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FirstProject/src/objects/Product_Table__c.object
<CustomObject>
    <description>Information about those products wich will be placing into basket</description>
    <fields>
        <fullName>Image_Url__c</fullName>
        <label>Image_Url</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Product_Description__c</fullName>
        <label>Product Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Units_Available__c</fullName>
        <label>Units Available</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Product Table</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FirstProject/src/classes/ProductBuyingController.cls
public class ProductBuyingController {
    
    public string email{get;set;}
    public string fname{get;set;}
    public string lname{get;set;}
    public Integer amount{get;set;}
    public boolean hasError{get;private set;}
    private Id idcontact;
    private Product_Table__c p;
    
    public PageReference getContact(){
        List<Contact> c = new List<Contact>();
        c = [select Email, FirstName, LastName from Contact where Email =: email limit 1];
        if(c.size() > 0){
            c[0].FirstName = fname;
            c[0].lastname = lname;
            upsert c;
        }else if(c.size() == 0){
            Contact tmpcon = new Contact();
            tmpcon.Email = email;
            tmpcon.FirstName = fname;
            tmpcon.LastName = lname;
            c.add(tmpcon);
            insert c;
        }
        idcontact = c[0].id;
        return null;
    }
    
    public Product_Table__c getProduct(){
        p = [select id, Name, Product_description__c, Unit_Price__c, Units_available__c, Image_Url__c
                    from Product_Table__c 
                	where id =: ApexPages.currentPage().getParameters().get('id') limit 1];
        return p;
    }
    
    public PageReference Save(){
        Order_Table__c order = new Order_Table__c();
        order.Contact__c = idcontact;
        order.Order_Amount__c = p.unit_price__c*amount;
        order.Product__c = p.id;
        order.Units__c = amount;
        p.Units_Available__c = p.Units_Available__c - amount;
        try{
            insert order;
            upsert p;
            hasError = false;
            return null;
        }catch(Exception e){
            system.debug('Error');
            hasError = true;
            return null;
        }
    }
    public PageReference toShopping(){
        return new PageReference('/Apex/ProductList');
    }
}