FirstProject/src/objects/Product_Table__c.object
<CustomObject>
    <description>Information about those products wich will be placing into basket</description>
    <fields>
        <fullName>Image_Url__c</fullName>
        <label>Image_Url</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Product_Description__c</fullName>
        <label>Product Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Product Table</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FirstProject/src/classes/ProductListController.cls
public class ProductListController {
    
    private List<Product_Table__c>plist;
    public Id pid{get;set;}
    
    public List<Product_Table__c>getProductList(){
        plist = new List<Product_Table__c>();
        plist = [select Image_Url__c, Name, Product_Description__c, Unit_Price__c from Product_Table__c];
        for(Product_Table__c pl:plist){
            String temp = pl.Product_Description__c;
            if(temp.length()>=100){
                pl.Product_Description__c = temp.substring(0,100);
            }
        }
        return plist;
    }
    public PageReference toBuying(){
        return new PageReference('/Apex/ProductBuying?id='+pid);
    }
}