FirstProject/src/objects/Product_Table__c.object
<CustomObject>
    <description>Information about those products wich will be placing into basket</description>
    <fields>
        <fullName>Image_Url__c</fullName>
        <label>Image_Url</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Product_Description__c</fullName>
        <label>Product Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Units_Available__c</fullName>
        <label>Units Available</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Product Table</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FirstProject/src/classes/ProductDetailController.cls
public class ProductDetailController {
    
    public Id pid{get;set;}
    
    public Product_Table__c getProduct(){
        Product_Table__c[] p = [select id, Name, Product_description__c, Unit_Price__c, Units_available__c, Image_Url__c 
                               from Product_Table__c 
                               where id =: ApexPages.currentPage().getParameters().get('id')];
        return p[0];
    }
    
    public PageReference toShopping(){
        return new PageReference('/Apex/ProductList');
    }
    public PageReference toBuying(){
        return new PageReference('/Apex/ProductBuying?id='+pid);
    }
}